-- 1. Create Projects Table
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  tech text[], -- Array of strings for tech stack
  demo_url text,
  code_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Messages Table
create table messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table projects enable row level security;
alter table messages enable row level security;

-- 4. Policies for Projects
-- Anyone can read projects
create policy "Public projects are viewable by everyone" 
on projects for select 
using (true);

-- Only authenticated users (Admins) can insert/delete projects
create policy "Admins can insert projects" 
on projects for insert 
to authenticated 
with check (true);

create policy "Admins can delete projects" 
on projects for delete 
to authenticated 
using (true);

-- 5. Policies for Messages
-- Anyone can insert a message (Contact Form)
create policy "Public can insert messages" 
on messages for insert 
with check (true);

-- Only authenticated users (Admins) can read messages
create policy "Admins can view messages" 
on messages for select 
to authenticated 
using (true);
